---
title: "examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE, comment = "#>",
    warning = FALSE, message = FALSE, error = FALSE,
    fig.align = "center", fig.width = 16, fig.height = 9, out.width = "100%"
)
```

```{r setup}
library(LearnNonparam)
```

# Chapter 1

## Example 1.1.2

```{r}
# See ?Quantile or ?onesample.quantile
t <- pmt(
    "onesample.quantile", alternative = "greater",
    p = 0.5, null_value = 75
)

# See ?Table1.1.1
t$feed(Table1.1.1)

print(t$statistic)
print(t$p_value)
print(t$ci)
```

## Example 1.2.1

```{r}
# See ?CDF or ?onesample.cdf
t <- pmt("onesample.cdf")

# See ?Table1.2.1
t$feed(Table1.2.1)

t$plot()
```

## Example 1.2.4

```{r}
# See ?Quantile or ?onesample.quantile
t <- pmt(
    "onesample.quantile",
    p = 0.25, null_value = 0, conf_level = 0.90
)

# See ?Table1.2.1
t$feed(Table1.2.1)

print(t$ci)
```

\newpage

# Chapter 2

## Example 2.1.1

```{r}
# See ?MeanDiff or ?twosample.mean
t <- pmt(
    "twosample.mean", alternative = "greater"
)

# See ?Table2.1.1
t$feed(Table2.1.1)
# or
# t$feed(
#     Table2.1.1$new,
#     Table2.1.1$traditional
# )

print(t$statistic)
print(t$p_value)
```

## Example 2.1.1 - wilcoxon

```{r}
# See ?Wilcoxon or ?twosample.wilcoxon
t <- pmt(
    "twosample.wilcoxon", alternative = "greater"
)

# See ?Table2.1.1
t$feed(Table2.1.1)
# or
# t$feed(
#     Table2.1.1$new,
#     Table2.1.1$traditional
# )

print(t$statistic)
print(t$p_value)
```

## Example 2.3.1

```{r}
start <- proc.time()

# See ?MeanDiff or ?twosample.mean
t <- pmt(
    "twosample.mean", alternative = "greater"
)

# See ?Table2.3.1
t$feed(Table2.3.1)
# or
# t$feed(
#     Table2.3.1$treatment_1,
#     Table2.3.1$treatment_2
# )

print(t$statistic)
print(t$p_value)

end <- proc.time()

# time: all permutaions
print(end - start)


start <- proc.time()

t$n_permu <- 1000

print(t$p_value)

end <- proc.time()

# time: 1000 permutaions
print(end - start)
```

## Example 2.6.1

```{r}
# See ?Wilcoxon or ?twosample.wilcoxon
t <- pmt(
    "twosample.wilcoxon", alternative = "greater"
)

# See ?Table2.6.1
t$feed(Table2.6.1)
# or
# t$feed(
#     Table2.6.1$brand_2,
#     Table2.6.1$brand_1
# )

print(t$statistic)
print(t$p_value)
```

## Example 2.6.2

```{r}
# See ?Wilcoxon or ?twosample.wilcoxon
t <- pmt(
    "twosample.wilcoxon", conf_level = 0.90
)

# See ?Table2.6.2
t$feed(Table2.6.2)
# or
# t$feed(
#     Table2.6.2$granite,
#     Table2.6.2$basalt
# )

# Hodges-Lehmann estimate
print(t$estimate)
print(t$ci)
```

## Example 2.7.1

```{r}
# See ?ScoreSum or ?twosample.scoresum
t <- pmt(
    "twosample.scoresum", alternative = "greater", scoring = "expon"
)

# See ?Table2.6.2
t$feed(Table2.6.2)
# or
# t$feed(
#     Table2.6.2$granite,
#     Table2.6.2$basalt
# )

print(t$statistic)
print(t$p_value)
```

## Example 2.8.1

```{r}
# See ?SiegelTukey or ?twosample.siegel
t <- pmt(
    "twosample.siegel", alternative = "less", type = "approx"
)

# See ?Table2.8.1
t$feed(Table2.8.1)
# or
# t$feed(
#     Table2.8.1$treatment_1,
#     Table2.8.1$treatment_2
# )

print(t$statistic)
print(t$p_value)
```

## Example 2.8.2

```{r}
# See ?RatioMeanDeviance or ?twosample.rmd
t <- pmt(
    "twosample.rmd", alternative = "greater"
)

# See ?Table2.8.1
t$feed(Table2.8.1)
# or
# t$feed(
#     Table2.8.1$treatment_1,
#     Table2.8.1$treatment_2
# )

print(t$statistic)
print(t$p_value)
```

## Example 2.8.3

```{r}
# See ?KolmogorovSmirnov or ?twosample.ks
t <- pmt(
    "twosample.ks", n_permu = 5000
)

# See ?Table2.8.1
t$feed(Table2.8.1)
# or
# t$feed(
#     Table2.8.1$treatment_1,
#     Table2.8.1$treatment_2
# )

print(t$statistic)
print(t$p_value)
```

\newpage

# Chapter 3

## Example 3.1.1

```{r}
# See ?ANOVA or ?ksample.anova
t <- pmt(
    "ksample.anova", type = "approx"
)

# See ?Table3.1.2
t$feed(Table3.1.2)
# or
# t$feed(
#     Table3.1.2$x_1,
#     Table3.1.2$x_2,
#     Table3.1.2$x_3
# )

# F-statistic
print(t$statistic)
print(t$p_value)


# Change n_permu first,
# otherwise changing type to permu will use all permutations by default,
# which results in an error because there are too many permutations. 
t$n_permu <- 1000
t$type <- "permu"


print(t$statistic)
print(t$p_value)
```

## Example 3.2.1

```{r}
# See ?KruskalWallis or ?ksample.kw
t <- pmt(
    "ksample.kw", type = "approx"
)

# See ?Table3.2.2
t$feed(Table3.2.2)
# or
# t$feed(
#     Table3.2.2$control,
#     Table3.2.2$preservative_1,
#     Table3.2.2$preservative_2,
#     Table3.2.2$preservative_3
# )

print(t$statistic)
print(t$p_value)
```

## Example 3.2.2 & 3.2.3

```{r}
# See ?KruskalWallis or ?ksample.kw
t <- pmt(
    "ksample.kw", n_permu = 4000
)

# See ?Table3.2.3
t$feed(Table3.2.3)
# or
# t$feed(
#     Table3.2.3$product_1,
#     Table3.2.3$product_2,
#     Table3.2.3$product_3
# )

print(t$statistic)
print(t$p_value)


t$type <- "approx"
print(t$p_value)


t$scoring <- "expon"

t$n_permu <- 4000
t$type <- "permu"
print(t$p_value)

t$type <- "approx"
print(t$p_value)
```

## Example 3.3.1

```{r}
# See ?MultiCompT or ?multicomp.t
t <- pmt(
    "multicomp.t", n_permu = 5000
)

# See ?Table3.3.1
t$feed(Table3.3.1)
# or
# t$feed(
#     Table3.3.1$location_1,
#     Table3.3.1$location_2,
#     Table3.3.1$location_3,
#     Table3.3.1$location_4
# )

print(t$multicomp)

t$type <- "approx"
print(t$multicomp)

# try other scoring! ("vw", "expon")
t$scoring <- "rank"
print(t$multicomp)
```

```{r}
# See ?TukeyHSD or ?multicomp.tukey
t <- pmt(
    "multicomp.tukey", n_permu = 5000
)

t$feed(Table3.3.1)

print(t$multicomp)

t$type <- "approx"
print(t$multicomp)

# try other scoring! ("vw", "expon")
t$scoring <- "rank"
print(t$multicomp)
```

## Example 3.4.1

```{r}
# See ?JonckheereTerpstra or ?ksample.jt
t <- pmt(
    "ksample.jt", alternative = "greater", n_permu = 4000
)

# See ?Table3.4.1
t$feed(Table3.4.1)
# or
# t$feed(
#     Table3.4.1$treatment_1,
#     Table3.4.1$treatment_2,
#     Table3.4.1$treatment_3,
#     Table3.4.1$treatment_4
# )

print(t$statistic)
print(t$p_value)

t$type <- "approx"
print(t$p_value)
```

\newpage

# Chapter 4

## Table 4.1.1

```{r}
# See ?PairedComparison or ?paired.comparison
t <- pmt(
    "paired.comparison", alternative = "greater"
)

# See ?Table4.1.1
t$feed(Table4.1.1)
# or
# t$feed(
#     Table4.1.1$recall_24h,
#     Table4.1.1$survey
# )

print(t$statistic)
print(t$p_value)

t$n_permu <- 4000
print(t$p_value)
```

## Table 4.1.3

```{r}
# See ?PairedComparison or ?paired.comparison
t <- pmt(
    "paired.comparison", alternative = "two_sided", n_permu = 4000
)

# See ?Table4.1.3
t$feed(Table4.1.3)
# or
# t$feed(
#     Table4.1.3$drug_1,
#     Table4.1.3$drug_2
# )

print(t$p_value)

t$type <- "approx"
print(t$p_value)
```

## Example 4.2.1 & 4.2.2

```{r}
# See ?Sign or ?paired.signedScore or ?paired.signedscore
t <- pmt(
    "paired.signedscore", alternative = "greater",
    ranking_method = "with_zeros"
)

# See ?Table4.1.1
t$feed(Table4.1.1)
# or
# t$feed(
#     Table4.1.1$recall_24h,
#     Table4.1.1$survey
# )

print(t$statistic)
print(t$p_value)

t$n_permu <- 4000
print(t$p_value)

t$type <- "approx"
print(t$p_value)
```

## Table 4.2.3

```{r}
# See ?Sign or ?paired.signedScore or ?paired.signedscore
t <- pmt(
    "paired.signedscore", alternative = "greater",
    ranking_method = "ignore"
)

t$feed(data.frame(
    diff = c(-5, -3, -3, 0, 0, 2, 4, 4, 4, 5),
    zero = 0
))

print(t$statistic)
print(t$p_value)

t$n_permu <- 4000
print(t$p_value)
```

## Example 4.3.1

```{r}
# See ?Sign or ?paired.sign
t <- pmt(
    "paired.sign", alternative = "greater"
)

t$feed(data.frame(
    diff = c(rep(+1, 12), rep(-1, 5)),
    zero = 0
))

print(t$statistic)
print(t$p_value)

t$type <- "approx"
print(t$p_value)
```

## Example 4.4.1

```{r}
# See ?RCBDANOVA or ?rcbd.anova
t <- pmt(
    "rcbd.anova", n_permu = 5000
)

# See ?Table4.4.3
t$feed(Table4.4.3)
# or
# t$feed(
#     Table4.4.3$block_1,
#     Table4.4.3$block_2,
#     Table4.4.3$block_3,
#     Table4.4.3$block_4,
#     Table4.4.3$block_5,
#     Table4.4.3$block_6
# )


print(t$statistic)
print(t$p_value)


t$type <- "approx"
# F-statistic
print(t$statistic)
print(t$p_value)
```

## Example 4.5.2

```{r}
# See ?Friedman or ?rcbd.friedman
t <- pmt(
    "rcbd.friedman", n_permu = 5000
)

# See ?Table4.5.3
t$feed(Table4.5.3)
# or
# t$feed(
#     Table4.5.3$block_1,
#     Table4.5.3$block_2,
#     Table4.5.3$block_3
# )

# Use SSX for speed
print(t$statistic)
print(t$p_value)


t$type <- "approx"
# chi-statistic
print(t$statistic)
print(t$p_value)
```

## Example 4.6.1

```{r}
# See ?Page or ?rcbd.page
t <- pmt(
    "rcbd.page", alternative = "less", n_permu = 5000
)

# See ?Table4.4.3
t$feed(Table4.4.3)
# or
# t$feed(
#     Table4.4.3$block_1,
#     Table4.4.3$block_2,
#     Table4.4.3$block_3,
#     Table4.4.3$block_4,
#     Table4.4.3$block_5,
#     Table4.4.3$block_6
# )

print(t$statistic)
print(t$p_value)


t$type <- "approx"
print(t$p_value)
```

\newpage

# Chapter 5

## Example 5.1.1

```{r}
# See ?Correlation or ?association.corr
t <- pmt(
    "association.corr", method = "pearson",
    alternative = "greater", n_permu = 2000
)

# See ?Table5.1.2
t$feed(Table5.1.2)
# or
# t$feed(
#     Table5.1.2$heterophils,
#     Table5.1.2$lymphocytes
# )

print(t$statistic)
print(t$p_value)
```

## Example 5.2.1

```{r}
# See ?Correlation or ?association.corr
t <- pmt(
    "association.corr", method = "spearman",
    alternative = "greater", n_permu = 5000
)

# See ?Table5.1.2
t$feed(Table5.1.2)
# or
# t$feed(
#     Table5.1.2$heterophils,
#     Table5.1.2$lymphocytes
# )

print(t$statistic)
print(t$p_value)


t$type <- "approx"
print(t$p_value)
```

## Example 5.3.2

```{r}
# See ?Correlation or ?association.corr
t <- pmt(
    "association.corr", method = "kendall",
    alternative = "greater", type = "approx"
)

# See ?Table5.2.2
t$feed(Table5.2.2)
# or
# t$feed(
#     Table5.2.2$judge_a,
#     Table5.2.2$judge_b
# )

print(t$statistic)
print(t$p_value)
```

## Table 5.4.2

```{r}
# See ?ChiSquare or ?table.chi
t <- pmt(
    "table.chi", n_permu = 2000
)

# See ?Table5.4.2
t$feed(Table5.4.2)

print(t$statistic)
print(t$p_value)

t$type <- "approx"
print(t$p_value)
```
