# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

association_pmt <- function(x, y, statistic_func, n_permu) {
    .Call(`_LearnNonparam_association_pmt`, x, y, statistic_func, n_permu)
}

ksample_pmt <- function(data, group, statistic_func, n_permu) {
    .Call(`_LearnNonparam_ksample_pmt`, data, group, statistic_func, n_permu)
}

multicomp_pmt <- function(group_i, group_j, data, group, statistic_func, n_permu) {
    .Call(`_LearnNonparam_multicomp_pmt`, group_i, group_j, data, group, statistic_func, n_permu)
}

paired_pmt <- function(n, statistic_func, n_permu) {
    .Call(`_LearnNonparam_paired_pmt`, n, statistic_func, n_permu)
}

rcbd_pmt <- function(data, statistic_func, n_permu) {
    .Call(`_LearnNonparam_rcbd_pmt`, data, statistic_func, n_permu)
}

table_pmt <- function(row_loc, col_loc, statistic_func, n_permu) {
    .Call(`_LearnNonparam_table_pmt`, row_loc, col_loc, statistic_func, n_permu)
}

twosample_pmt <- function(data, where_y, statistic_func, n_permu) {
    .Call(`_LearnNonparam_twosample_pmt`, data, where_y, statistic_func, n_permu)
}

