# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ksample_pmt <- function(data, group, statistic_func, n_sample) {
    .Call(`_LearnNonparam_ksample_pmt`, data, group, statistic_func, n_sample)
}

twosample_pmt <- function(n_1, n_2, c_xy, statistic_func, n_sample) {
    .Call(`_LearnNonparam_twosample_pmt`, n_1, n_2, c_xy, statistic_func, n_sample)
}

