# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

association_pmt <- function(x, y, statistic_func, n_permu) {
    .Call(`_LearnNonparam_association_pmt`, x, y, statistic_func, n_permu)
}

ksample_pmt <- function(data, group, statistic_func, n_permu) {
    .Call(`_LearnNonparam_ksample_pmt`, data, group, statistic_func, n_permu)
}

paired_pmt <- function(n, statistic_func, n_permu) {
    .Call(`_LearnNonparam_paired_pmt`, n, statistic_func, n_permu)
}

rcbd_pmt <- function(data, statistic_func, n_permu) {
    .Call(`_LearnNonparam_rcbd_pmt`, data, statistic_func, n_permu)
}

twosample_pmt <- function(n_1, n_2, c_xy, statistic_func, n_permu) {
    .Call(`_LearnNonparam_twosample_pmt`, n_1, n_2, c_xy, statistic_func, n_permu)
}

